# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/EricProjects/EyeGore/Forms/Main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(188, 346)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/eyegore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CameraView = WebCamView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CameraView.sizePolicy().hasHeightForWidth())
        self.CameraView.setSizePolicy(sizePolicy)
        self.CameraView.setBaseSize(QtCore.QSize(100, 100))
        self.CameraView.setObjectName("CameraView")
        self.horizontalLayout.addWidget(self.CameraView)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_Camera = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Camera.sizePolicy().hasHeightForWidth())
        self.label_Camera.setSizePolicy(sizePolicy)
        self.label_Camera.setObjectName("label_Camera")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Camera)
        self.comboBoxCameraSelect = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxCameraSelect.setObjectName("comboBoxCameraSelect")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxCameraSelect)
        self.label_Comport = QtWidgets.QLabel(self.groupBox)
        self.label_Comport.setObjectName("label_Comport")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_Comport)
        self.comboBoxComport = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxComport.setObjectName("comboBoxComport")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxComport)
        self.pushButtonSave = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSave.sizePolicy().hasHeightForWidth())
        self.pushButtonSave.setSizePolicy(sizePolicy)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.pushButtonSave)
        self.checkBoxPause = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxPause.sizePolicy().hasHeightForWidth())
        self.checkBoxPause.setSizePolicy(sizePolicy)
        self.checkBoxPause.setObjectName("checkBoxPause")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.checkBoxPause)
        self.pushButtonSelectFolder = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelectFolder.sizePolicy().hasHeightForWidth())
        self.pushButtonSelectFolder.setSizePolicy(sizePolicy)
        self.pushButtonSelectFolder.setFlat(False)
        self.pushButtonSelectFolder.setObjectName("pushButtonSelectFolder")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButtonSelectFolder)
        self.plainText_FolderName = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainText_FolderName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainText_FolderName.sizePolicy().hasHeightForWidth())
        self.plainText_FolderName.setSizePolicy(sizePolicy)
        self.plainText_FolderName.setAcceptDrops(False)
        self.plainText_FolderName.setStyleSheet("color: rgb(0, 0, 0);")
        self.plainText_FolderName.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plainText_FolderName.setReadOnly(True)
        self.plainText_FolderName.setObjectName("plainText_FolderName")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.plainText_FolderName)
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignLeft)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EyeGore"))
        self.groupBox.setTitle(_translate("MainWindow", "Controls"))
        self.label_Camera.setText(_translate("MainWindow", "Camera"))
        self.label_Comport.setText(_translate("MainWindow", "Comport"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.checkBoxPause.setText(_translate("MainWindow", "Pause"))
        self.pushButtonSelectFolder.setText(_translate("MainWindow", "Select Folder"))

from Forms.WebCamView import WebCamView
import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

